name: projet_creation_playlist
description: "Application Flutter permettant de créer et partager une playlist musicale."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8


  share_plus: ^10.0.0


  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/photo1.png
    - assets/photo2.png
